# -*- coding: utf-8 -*-
"""Iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qLt4z8q-tRkYOex4VG5gcC5LhSghuI3O
"""

# mglearnインストール
!pip install mglearn

# Commented out IPython magic to ensure Python compatibility.
# 必要なライブラリのインポート
import sys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy as sp
import mglearn
from IPython.display import display
# グラフをブラウザ上に直接表示するコマンド
# %matplotlib inline

# データ読み込み
from sklearn.datasets import load_iris
iris_dataset = load_iris()

# データ表示
print("Key of iris_dataset: \n{}".format(iris_dataset.keys()))

# データセットの簡単な説明の最初の部分を確認(DESCR)
print(iris_dataset['DESCR'][:193] + "\n...")

# 予測しようとしている花の種類
print("Target names: {}".format(iris_dataset['target_names']))

# 花の特徴量
print("Feature names: {}".format(iris_dataset['feature_names']))

# データの詳細
print("Type of data: {}".format(type(iris_dataset['data'])))

# データの形(行,列)
print("Shape of data: {}".format(iris_dataset['data'].shape))

# 最初の5つのサンプルを確認
print("First five column of data: {}".format(iris_dataset['data'][:5]))

# 測定された個々の花の種類
print("Type of target: {}".format(type(iris_dataset['target'])))

# データの形
print("Shape of target: {}".format(iris_dataset['target'].shape))

# targetの中身確認
print("Target:\n{}".format(iris_dataset['target']))

